version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}

  testing_webserver:
    build: tests/integration/testing_webserver

  scraper:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      URL_TO_SCRAPE: ${URL_TO_SCRAPE}

# Waits for the databse to be accesible
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

# Waits for the testing webserver to be accesible
  start_dependencies_testing_webserver:
    image: dadarek/wait-for-dependencies
    depends_on:
      - testing_webserver
    command: testing_webserver:8080
